language: python
# ===== Linux ======
os: linux
dist: xenial
python:
  - 3.9
jobs:
  include:
    - name: "Python 3.8.0 on macOS 10.14"
      os: osx
      osx_image: xcode11.3  # Python 3.8.0 running on macOS 10.14.6
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - python3 -m pip install --upgrade codecov pytest
      script: python3 -m pytest
      after_success: python3 -m codecov
    #  ====== WINDOWS =========
    - name: "Python 3.9.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.9.2
        - python --version
        - python -m pip install --upgrade pip
        - python -m pip install --upgrade codecov pytest
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
before_install:
  - python --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade codecov pytest
install:
  - pip install ".[test]"
script: pytest
after_success:
  - codecov # submit coverage
